version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - dev.env
    ports:
      - "9001:9001"
    volumes:
    - .:/app
    - /app/.venv

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - dev.env
    entrypoint: "bash"
    volumes:
    - .:/app
    - /app/.venv   

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile-jupyter
      args:
        BUILD_ENV: jupyter
    env_file:
      - dev.env
    entrypoint: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
    ports:
      - "8888:8888"
    volumes:
    - .:/app
    - /app/.venv

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
      args:
        BUILD_ENV: test
    env_file:
      - dev.env
    entrypoint: pytest tests
    volumes:
    - .:/app
    - /app/.venv